### ISSUE TITLE
Extra results from Julia

### ISSUE THREAD

**Issue by chenzjames** [PaulSoderlind/PaulSoderlindCode#1]
Hi Paul, 
I am new to GitHub, sorry that if I use this "issue" wrongly.

I found that your tutorial is great and was wondering if there is an efficient way to extra results (especial computation results with variables' names and their value) to "txt" or "csv". In your tutorial for writing into txt, "\n" does not work well. Besides, the DataFrame package is not easy to use.

**Comment by PaulSoderlind** [comment]
Hi,
you could either do like
println(fh,"x")
println(fh,x)

or (perhaps easier) use a jupyter notebook.    

As for \n, it just creates a new line. 

/Paul

**Comment by chenzjames** [comment]
Thanks Paul and thank you for your tutorial in Github. I am changing to
notebook version of Julia. Previously I used the command line, which is
terrible for data output.

I also find the MAT package provides a quick way to write output data into
a .mat file.

Regards,
James
